#!/usr/bin/env bash


set -e


wget -O data.zip "https://megastore.rz.uni-augsburg.de/get/DZwvpWPBaw/"


unzip -q data.zip


# The archive contains a directory `data` with subdirectories.
data_dir=data


# Prevent overwriting files. On the server, only the weird Perl rename exists.
find "$data_dir/additional" -type f -exec rename 's/\./_add./' '{}' ';'


pushd "$data_dir"/additional


for dir in *; do
    mv "$dir"/* ../original/"$dir"
done


popd
