#!/usr/bin/env bash


if test -z "$1"; then
    echo "Requires argument: data directory"
    exit 1
fi


data_dir="$1"


pushd "$data_dir"/additional


# Prevent overwriting files.
rename "." "_add." **


for dir in *; do
    mv "$dir"/* ../original/"$dir"
done


popd


dir=$(mktemp --dry-run --directory)
mv "$data_dir" "$dir"
mv "$dir"/original "$data_dir"
