#!/usr/bin/env fish


set dir "/run/media/david/intenso"
set n_samples 20


# None


# 2022-06-08-07-00-13 Falken.ts gegen Mitte
# 2022-06-08-16-33-13 Falken.ts gegen Anfang
# 2022-06-08-16-33-13 Falken.ts gegen Mitte
# 2022-06-08-20-02-30 Falken.ts gegen Anfang
# 2022-06-08-20-32-24 Falken.ts gegen Mitte
./sample_from_video_file.py "$dir/2022-06-08-07-30-09 Falken.ts" --start=00:00 --end=12:03 --n-samples="$n_samples"
./sample_from_video_file.py "$dir/2022-06-08-09-59-49 Falken.ts" --start=20:21 --end=24:19 --n-samples="$n_samples"
./sample_from_video_file.py "$dir/2022-06-08-14-33-36 Falken.ts" --start=01:20 --end=03:48 --n-samples="$n_samples"
./sample_from_video_file.py "$dir/2022-06-08-14-33-36 Falken.ts" --start=09:04 --end=17:32 --n-samples="$n_samples"


mv sample additional_no_falcons


# Both


# 2022-06-08-08-30-02 Falken.ts gegen Anfang
./sample_from_video_file.py "$dir/2022-06-08-09-29-55 Falken.ts" --start=17:52 --end=18:08 --n-samples="$n_samples"
./sample_from_video_file.py "$dir/2022-06-08-09-59-49 Falken.ts" --start=27:17 --end=27:30 --n-samples="$n_samples"
./sample_from_video_file.py "$dir/2022-06-08-20-32-24 Falken.ts" --start=21:03 --end=26:54 --n-samples="$n_samples"


mv sample additional_both


# Tom


./sample_from_video_file.py "$dir/2022-06-08-16-33-13 Falken.ts" --start=05:31 --end=12:00 --n-samples="$n_samples"


mv sample additional_tom
